name: flutter_cleanframework_todo_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  clean_framework: ^3.2.3
  clean_framework_http: ^0.4.1
  clean_framework_router: ^0.5.5
  dio: ^5.3.3
  flutter:
    sdk: flutter
  lottie: ^2.6.0
  pretty_dio_logger: ^1.3.1
  uniform: ^2.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
